#!/bin/bash
# mbhSysteminformation 
# 2019-04-06 Sat 17:48:56 KW:14 
# MBH # 
# Description: # 
#  
# Version:  # 
echo ""
echo "-------------------uname -a"
uname -a
echo ""
echo "-------------------lsb_release -a"
lsb_release -a
echo ""
echo "-------------------cat /etc/*release"
cat /etc/*release
echo ""
echo "-------------------cat /proc/version"
cat /proc/version
echo ""
echo "-------------------cat /proc/issue*"
cat /etc/issue*


